spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088" 
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: department-service
            uri: lb://department-service
            predicates:
            - Path=/department/**
          - id: employee-service
            uri: lb://employee-service
            predicates:
            - Path=/employee/**
server:
  port: 8060
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0